import { writeFileSync } from 'node:fs';

/** Path data for a rounded rectangle, so the icon geometry is exact. */
function roundedRect(x, y, w, h, r) {
  const n = (v) => Number(v.toFixed(2));
  return [
    `M${n(x + r)},${n(y)}`,
    `H${n(x + w - r)}`,
    `A${n(r)},${n(r)} 0 0 1 ${n(x + w)},${n(y + r)}`,
    `V${n(y + h - r)}`,
    `A${n(r)},${n(r)} 0 0 1 ${n(x + w - r)},${n(y + h)}`,
    `H${n(x + r)}`,
    `A${n(r)},${n(r)} 0 0 1 ${n(x)},${n(y + h - r)}`,
    `V${n(y + r)}`,
    `A${n(r)},${n(r)} 0 0 1 ${n(x + r)},${n(y)}`,
    'Z',
  ].join(' ');
}

// A bed: instantly readable as "hotel" even at launcher size.
// Everything sits inside the 72x72 safe zone of the 108x108 adaptive viewport.
const parts = [
  roundedRect(24, 34, 9, 38, 4.5),   // headboard
  roundedRect(37, 42, 17, 11, 5.5),  // pillow
  roundedRect(33, 53, 51, 13, 6.5),  // mattress
  roundedRect(24, 66, 60, 6, 3),     // base
];

const vector = (size, color) => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/gen-icon.mjs - a bed mark, white on brand blue. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${size}dp"
    android:height="${size}dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
${parts.map((d) => `    <path\n        android:fillColor="${color}"\n        android:pathData="${d}" />`).join('\n')}
</vector>
`;

writeFileSync('android/app/src/main/res/drawable/ic_hotel_mark.xml', vector(108, '#FFFFFF'));
console.log('wrote drawable/ic_hotel_mark.xml');
